language: node_js
node_js:
  - "node"
cache:
  directories:
    - $HOME/.npm
    - node_modules
install:
  - npm install
before_script:
  - npm run bootstrap
  - npm run build
script:
  - npm run test